# Generated by Django 5.2.1 on 2025-08-05 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regno', models.IntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('sub1', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('sub2', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('sub3', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
