# Generated by Django 5.2.1 on 2025-08-05 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='regno',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
