# Generated by Django 5.2.1 on 2025-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_marks_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='regno',
            field=models.IntegerField(),
        ),
    ]
